# compila los ejemplos en todas las placas soportadas

name: Compilar ejemplos

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - examples/**
      - library.properties
      - .github/workflows/arduino.yml
  pull_request:

jobs:
  compilar:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        placa:
          - fqbn: arduino:samd:nano_33_iot
            plataformas: |
              - name: arduino:samd
          - fqbn: rp2040:rp2040:rpipicow
            plataformas: |
              - name: rp2040:rp2040
                source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          - fqbn: rp2040:rp2040:rpipico2w
            plataformas: |
              - name: rp2040:rp2040
                source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.placa.fqbn }}
          platforms: ${{ matrix.placa.plataformas }}
          sketch-paths: |
            - examples/
          enable-warnings-report: true
          libraries: |
            - source-path: ./
            - name: ArduinoJson
            - name: WiFiNINA
